// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwXjMbTEaL2xIzDJU5V-s3B9r85Itv7n4',
    appId: '1:80285161494:web:2687ccd1f97c70b1f4fd37',
    messagingSenderId: '80285161494',
    projectId: 'challengemax-f20b5',
    authDomain: 'challengemax-f20b5.firebaseapp.com',
    storageBucket: 'challengemax-f20b5.firebasestorage.app',
    measurementId: 'G-DE0QXTX0K8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvfcCfrj9nZmF5bwLOFaZOHfbaZTJ1QlM',
    appId: '1:80285161494:android:e4cd5b31fbcf3188f4fd37',
    messagingSenderId: '80285161494',
    projectId: 'challengemax-f20b5',
    storageBucket: 'challengemax-f20b5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVlzP4A4q1uOZdhqNi0lTO37MnjTO7el4',
    appId: '1:80285161494:ios:708877a616732769f4fd37',
    messagingSenderId: '80285161494',
    projectId: 'challengemax-f20b5',
    storageBucket: 'challengemax-f20b5.firebasestorage.app',
    iosBundleId: 'com.example.challengeMax',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVlzP4A4q1uOZdhqNi0lTO37MnjTO7el4',
    appId: '1:80285161494:ios:708877a616732769f4fd37',
    messagingSenderId: '80285161494',
    projectId: 'challengemax-f20b5',
    storageBucket: 'challengemax-f20b5.firebasestorage.app',
    iosBundleId: 'com.example.challengeMax',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDwXjMbTEaL2xIzDJU5V-s3B9r85Itv7n4',
    appId: '1:80285161494:web:8e2a2b3aa37363dcf4fd37',
    messagingSenderId: '80285161494',
    projectId: 'challengemax-f20b5',
    authDomain: 'challengemax-f20b5.firebaseapp.com',
    storageBucket: 'challengemax-f20b5.firebasestorage.app',
    measurementId: 'G-GRZWVHM2JJ',
  );
}
